name: Dashboard v1.0.0

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Feds Dash iOS Build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Link ios folder into dash
        run: ln -s ${{ github.workspace }}/ios ${{ github.workspace }}/dash/ios

      - run: flutter pub get
        working-directory: dash

      - name: Generate iOS app icons
        run: flutter pub run flutter_launcher_icons
        working-directory: dash

      - run: flutter build ios --release --no-codesign
        working-directory: dash

      - run: mkdir Payload
        working-directory: dash/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: dash/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 "Feds Dash v1.0.0.ipa" Payload
        working-directory: dash/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "dash/build/ios/iphoneos/Feds Dash v1.0.0.ipa"
          tag: v1.0.0
          release_name: Dashboard v1.0.0
          overwrite: true
          body: "first release"
